/**
 * Economic participation state and activation. No subscriptions, no pricing.
 * Value generated by the environment creates economic participation automatically.
 */

import { getDb } from "@/lib/db/queries";

export type ParticipationReason =
  | "value_generated"
  | "value_protected"
  | "coordination_dependency";

export type ActivationSource =
  | "recovered_value"
  | "network_dependency"
  | "protected_outcome";

export type UsageType =
  | "commitments_resolved"
  | "payments_recovered"
  | "opportunities_revived"
  | "shared_entries_created";

const NOW = () => new Date().toISOString();

/**
 * Upsert economic_participation for (workspace_id, participation_reason). Set last_detected_at, then recompute economic_active.
 */
export async function upsertParticipation(
  workspaceId: string,
  participationReason: ParticipationReason,
  now: string = NOW()
): Promise<void> {
  const db = getDb();
  const { data: row } = await db
    .from("economic_participation")
    .select("id, first_detected_at")
    .eq("workspace_id", workspaceId)
    .eq("participation_reason", participationReason)
    .maybeSingle();

  if (!row) {
    await db.from("economic_participation").insert({
      workspace_id: workspaceId,
      participation_reason: participationReason,
      first_detected_at: now,
      last_detected_at: now,
      economic_active: false,
    });
  } else {
    await db
      .from("economic_participation")
      .update({ last_detected_at: now })
      .eq("workspace_id", workspaceId)
      .eq("participation_reason", participationReason);
  }

  await recomputeEconomicActive(workspaceId);
}

/**
 * Set economic_active = true on all participation rows for workspace when ≥2 distinct participation_reason exist.
 */
export async function recomputeEconomicActive(workspaceId: string): Promise<void> {
  const db = getDb();
  const { data: rows } = await db
    .from("economic_participation")
    .select("participation_reason")
    .eq("workspace_id", workspaceId);
  const reasons = new Set((rows ?? []).map((r: { participation_reason: string }) => r.participation_reason));
  const economicActive = reasons.size >= 2;
  await db
    .from("economic_participation")
    .update({ economic_active: economicActive })
    .eq("workspace_id", workspaceId);
}

/**
 * Insert economic_activation when economic_active and no row exists. No user notification.
 */
export async function ensureActivation(workspaceId: string): Promise<boolean> {
  const db = getDb();
  const { data: existing } = await db
    .from("economic_activation")
    .select("id")
    .eq("workspace_id", workspaceId)
    .maybeSingle();
  if (existing) return false;

  const { data: parts } = await db
    .from("economic_participation")
    .select("participation_reason")
    .eq("workspace_id", workspaceId)
    .eq("economic_active", true);
  const reasons = new Set((parts ?? []).map((p: { participation_reason: string }) => p.participation_reason));
  let activationSource: ActivationSource = "recovered_value";
  if (reasons.has("value_protected")) activationSource = "protected_outcome";
  else if (reasons.has("coordination_dependency")) activationSource = "network_dependency";

  await db.from("economic_activation").insert({
    workspace_id: workspaceId,
    activated_at: NOW(),
    activation_source: activationSource,
  });
  return true;
}

/**
 * True if workspace has an economic_activation row.
 */
export async function hasEconomicActivation(workspaceId: string): Promise<boolean> {
  const db = getDb();
  const { count } = await db
    .from("economic_activation")
    .select("id", { count: "exact", head: true })
    .eq("workspace_id", workspaceId);
  return (count ?? 0) > 0;
}

/**
 * Set usage meter row for a period. Idempotent: upsert by (workspace_id, period_start, usage_type) so daily cron can run repeatedly.
 */
export async function setUsageMeter(
  workspaceId: string,
  periodStart: string,
  periodEnd: string,
  usageType: UsageType,
  count: number
): Promise<void> {
  const db = getDb();
  const { data: existing } = await db
    .from("economic_usage_meter")
    .select("id")
    .eq("workspace_id", workspaceId)
    .eq("period_start", periodStart)
    .eq("usage_type", usageType)
    .maybeSingle();
  if (existing) {
    await db
      .from("economic_usage_meter")
      .update({ usage_count: count, period_end: periodEnd })
      .eq("id", (existing as { id: string }).id);
  } else {
    await db.from("economic_usage_meter").insert({
      workspace_id: workspaceId,
      period_start: periodStart,
      period_end: periodEnd,
      usage_type: usageType,
      usage_count: count,
    });
  }
}

/**
 * Aggregate usage for a period from engines (economic_events and shared_transactions / incoming_entries) and append meter rows.
 */
export async function aggregateAndAppendUsageForPeriod(
  workspaceId: string,
  periodStart: string,
  periodEnd: string
): Promise<void> {
  const db = getDb();

  const { data: events } = await db
    .from("economic_events")
    .select("event_type")
    .eq("workspace_id", workspaceId)
    .gte("created_at", periodStart)
    .lt("created_at", periodEnd);
  const list = (events ?? []) as { event_type: string }[];
  let commitmentsResolved = 0;
  let paymentsRecovered = 0;
  let opportunitiesRevived = 0;
  for (const e of list) {
    if (e.event_type === "commitment_saved") commitmentsResolved += 1;
    else if (e.event_type === "payment_recovered") paymentsRecovered += 1;
    else if (e.event_type === "opportunity_recovered") opportunitiesRevived += 1;
  }

  const { count: sharedCount } = await db
    .from("shared_transactions")
    .select("id", { count: "exact", head: true })
    .eq("workspace_id", workspaceId)
    .gte("created_at", periodStart)
    .lt("created_at", periodEnd);
  const sharedEntriesCreated = sharedCount ?? 0;

  await setUsageMeter(workspaceId, periodStart, periodEnd, "commitments_resolved", commitmentsResolved);
  await setUsageMeter(workspaceId, periodStart, periodEnd, "payments_recovered", paymentsRecovered);
  await setUsageMeter(workspaceId, periodStart, periodEnd, "opportunities_revived", opportunitiesRevived);
  await setUsageMeter(workspaceId, periodStart, periodEnd, "shared_entries_created", sharedEntriesCreated);
}
