name: Operator

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://YOURDOMAIN.com/api/cron/process-queue
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://YOURDOMAIN.com/api/cron/calendar-ended
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" https://YOURDOMAIN.com/api/cron/zoom-refresh
